config/routes.rb
Rails.application.routes.draw do
  resources :pic_comments
  devise_for :users
  resources :pics do 
    member do
      put "like", to: "pics#upvote"
    end
  end
  root "pics#index"

end

app/models/pic.rb
class Pic < ActiveRecord::Base
    acts_as_votable
    belongs_to :user
    has_many :pic_comment, ->{order "created_at DESC "}
    
    has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/pic_comment.rb
class PicComment < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :pics
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pic_comments_controller.rb
class PicCommentsController < ApplicationController
  before_action :set_pic_comment, only: [:show, :edit, :update, :destroy]

  # GET /pic_comments
  # GET /pic_comments.json
  def index
    @pic_comments = PicComment.all
  end

  # GET /pic_comments/1
  # GET /pic_comments/1.json
  def show
  end

  # GET /pic_comments/new
  def new
    @pic_comment = PicComment.new
  end

  # GET /pic_comments/1/edit
  def edit
  end

  # POST /pic_comments
  # POST /pic_comments.json
  def create
    @pic_comment = PicComment.new(pic_comment_params)
    @pic_comment.user_id = current_user.id
    respond_to do |format|
      if @pic_comment.save
        url = "/pics/" + @pic_comment.pic_id.to_s
        format.html { redirect_to url, notice: 'Pic comment was successfully created.' }
        format.json { render :show, status: :created, location: @pic_comment }
      else
        format.html { render :new }
        format.json { render json: @pic_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pic_comments/1
  # PATCH/PUT /pic_comments/1.json
  def update
    respond_to do |format|
      if @pic_comment.update(pic_comment_params)
        format.html { redirect_to @pic_comment, notice: 'Pic comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @pic_comment }
      else
        format.html { render :edit }
        format.json { render json: @pic_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pic_comments/1
  # DELETE /pic_comments/1.json
  def destroy
    @pic_comment.destroy
    respond_to do |format|
      format.html { redirect_to pic_comments_url, notice: 'Pic comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pic_comment
      @pic_comment = PicComment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pic_comment_params
      params.require(:pic_comment).permit(:user_id, :pic_id, :commemt)
    end
end

app/controllers/pics_controller.rb
class PicsController < ApplicationController
    
    before_action :find_pic, only: [:show,:edit, :update, :destroy, :upvote]
    before_action :authenticate_user!, except: [:index , :show] 
    def index
        @pics = Pic.all.order("created_at DESC")
    end
    
    def show 
        @pic_comment = PicComment.new
    end
    
		
    
    def new
        @pic = current_user.pics.build
    end
    
    def create
        @pic =  current_user.pics.build(pic_params)
        if @pic.save
            redirect_to @pic , notice: "Yess! It was posted"
        else
            render 'new'
        end
    end
    
    def edit
    end
	
	def update
		if @pic.update(pic_params)
			redirect_to @pic , notice: "updated"
		else
			render 'edit'
		end
	end
    
    def destroy
		@pic.destroy
		redirect_to root_path
	end
    
    def upvote
        @pic.upvote_by current_user
        redirect_to :back
    end
        
    private

	def pic_params
		params.require(:pic).permit(:title,:discription,:image)
	end
	
	def find_pic
		@pic = Pic.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pic_comments_helper.rb
module PicCommentsHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/views/layouts/application.html.haml
%html
%head
	%title COURAGE!
	= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
	= javascript_include_tag 'application', 'data-turbolinks-track' => true
	= csrf_meta_tags
%body
	%nav.navbar.navbar-inverse
		.container
			.navbar-brand= link_to "COURAGE!",root_path
			-if user_signed_in?
				%ul.nav.navbar-nav.navbar-left
					%li= link_to "Gram It!", new_pic_path
					%li= link_to "Setting",edit_user_registration_path
					%li= link_to "Log out",destroy_user_session_path,method: :delete

			- else
				%ul.nav.navbar-nav.navbar-left
					%li= link_to "Join",new_user_registration_path
					%li= link_to "Log in",new_user_session_path
	.container
		= yield

app/views/pic_comments/_form.html.erb
<%= simple_form_for(@pic_comment) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :user_id %>
    <%= f.input :pic_id %>
    <%= f.input :commemt %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/pic_comments/edit.html.erb
<h1>Editing Pic Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @pic_comment %> |
<%= link_to 'Back', pic_comments_path %>

app/views/pic_comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Pic Comments</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Pic</th>
      <th>Commemt</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pic_comments.each do |pic_comment| %>
      <tr>
        <td><%= pic_comment.user_id %></td>
        <td><%= pic_comment.pic_id %></td>
        <td><%= pic_comment.commemt %></td>
        <td><%= link_to 'Show', pic_comment %></td>
        <td><%= link_to 'Edit', edit_pic_comment_path(pic_comment) %></td>
        <td><%= link_to 'Destroy', pic_comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pic comment', new_pic_comment_path %>

app/views/pic_comments/new.html.erb
<h1>New Pic Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', pic_comments_path %>

app/views/pic_comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @pic_comment.user_id %>
</p>

<p>
  <strong>Pic:</strong>
  <%= @pic_comment.pic_id %>
</p>

<p>
  <strong>Commemt:</strong>
  <%= @pic_comment.commemt %>
</p>

<%= link_to 'Edit', edit_pic_comment_path(@pic_comment) %> |
<%= link_to 'Back', pic_comments_path %>

app/views/pics/_form.html.haml
= simple_form_for @pic , html: {multipart: true } do |f|
	

	.form-group
		=f.input :image, input_html: {class: 'form-control'}
	.form-group
		=f.input :title, input_html: {class: 'form-control'}
	.form-group
		=f.input :discription, input_html: {class: 'form-control'}
	

	=f.button :submit, class: "btn btn-info"

app/views/pics/edit.html.haml
#edit_page.col-md-8.col-m-offset-2
    .row
        .panel.panel-default
            .panel-heading
                %h1 Edit Pic
            .panel-body
                .current_image
                    %strong.center Right Now
                    = image_tag @pic.image.url(:medium)
                = render 'form'

app/views/pics/index.html.haml
.col-md-12
    #pics.transitions-enabled
        - @pics.each do |pic|
            .box.panel.panel-default
                = link_to (image_tag pic.image.url), pic
                %h2= link_to pic.title,pic
    

app/views/pics/new.html.haml
.col-md-8.col-m-offset-2
    .row
        .panel.panel-default
            .panel-heading
                %h1 Post Pic
            .panel-body
                = render 'form'

app/views/pics/show.html.haml
#pic_show.row
    .col-md-6.col-md-offset-3
        .panel.panel-default
            .panel.heading.pic_image
                = image_tag @pic.image.url
            .panel-body
                %h1= @pic.title
                %p= @pic.discription
            .panel-footer
                .row
                    .col-md-6
                        %p.user
                            by
                            = @pic.user.email
                    .col-md-6
                        .btn-group.pull-right
                            = link_to like_pic_path(@pic), method: :put,class: "btn btn-default" do
                                %span.glyphicon.glyphicon-thumbs-up
                                = @pic.get_upvotes.size
                            
                            - if (user_signed_in?) && (@pic.user_id == current_user.id)
                                = link_to "Edit", edit_pic_path, class: "btn btn-info"
                                = link_to "Delete", pic_path, method: :delete, data: {confirm: "Are u sure?"}, class: "btn btn-danger"
                %br
                %br
                - if user_signed_in?
                    =  simple_form_for(@pic_comment) do |f|
                        .field
                            %br
                            .form-group
                                = f.input  :commemt, input_html: {class: 'form-control'}
                            %br
                                = f.hidden_field :pic_id, :value => @pic.id
                            %br
                        .actions
                        =f.button :submit, class: "btn btn-info"
                %h2 Comment
                %ul	
                    - @pic.pic_comment.each do |pic_comment|
                        %li= pic_comment.commemt